version: "3"

services:
  web:
    image: nginx:latest
    restart: always
    networks:
      - internal_netword
    ports:
      - 81:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/default.d:/etc/nginx/default.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/html
    depends_on:
      - php
      - mariadb

  php:
    build: ./php
    restart: always
    networks:
      - internal_netword
    volumes:
      - ./:/var/www/html

  mariadb:
    image: mariadb:latest
    restart: always
    networks:
      - internal_netword
    volumes:
      - ./db/datadir:/var/lib/mysql
    env_file:
      - .env

networks:
  internal_netword:
